primary_ping = 2 # in seconds
primary_promotion = 20 # in seconds

[server]
ip_v4 = "0.0.0.0"
ip_v6 = "::"
port = 22775

[cache]
driver = "rocksdb"

[db]
driver = "sqlite" # or "postgres" or "mysql"
min_connections = 5
max_connections = 100
connect_timeout = 8
idle_timeout = 8
max_lifetime = 8

[warehouse]
driver = "clickhouse"

[dsn]
rocksdb = "rocksdb://barreleye_cache"
sqlite = "sqlite://barreleye_database?mode=rwc"
postgres = "" # eg: "postgres://USERNAME[:PASSWORD]@localhost:5432/database"
mysql = "" # eg: "mysql://USERNAME[:PASSWORD]@localhost:3306/database"
clickhouse = "" # eg: "http://USERNAME[:PASSWORD]@localhost:8123/database"