[package]
name = "barreleye-common"
description = "Open-source blockchain analytics."
repository = "https://github.com/barreleye/barreleye"
documentation = "https://docs.rs/barreleye"
homepage = "https://barreleye.com"
version = "0.0.1"
license = "AGPL-3.0"
edition = "2021"
workspace = ".."

[dependencies]
async-trait = "0.1.66"
eyre = "0.6.8"
sea-orm-migration = "0.11.1"
nanoid = "0.4.0"
serde = "1.0.155"
log = "0.4.17"
derive_more = "0.99.17"
indicatif = "0.17.3"
serde_json = "1.0.94"
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std"] }
url = "2.3.1"
console = "0.15.5"
exitcode = "1.1.2"
bitcoin = "0.29.2"
directories = "4.0.1"
rocksdb = "0.20.1"
rmp-serde = "1.1.1"
regex = "1.7.1"
governor = "0.5.1"
base64 = "0.21.0"
itertools = "0.10.5"
futures = "0.3.27"
hex = "0.4.3"
num_cpus = "1.15.0"
bitcoincore-rpc-json = "0.16.0"
duckdb = { version = "0.7.1", features = ["bundled"] }
reqwest = { version = "0.11.14", features = ["rustls-tls"] }
tokio = { version = "1.26.0", features = ["full"] }
ethers = { version = "2.0.0", features = ["rustls"] }
clickhouse = { version = "0.11.3", features = ["uuid"] }
clap = { version = "4.1.8", features = ["cargo", "derive", "env"] }
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }

[dependencies.sea-orm]
version = "0.11.1"
features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "sqlx-mysql",
  "runtime-tokio-rustls"
]
