[package]
name = "barreleye-common"
version = "0.0.1"
license = "MPL-2.0"
edition = "2021"
workspace = ".."

[dependencies]
async-trait = "0.1.57"
eyre = "0.6.8"
sea-orm-migration = "0.10.2"
nanoid = "0.4.0"
serde = "1.0.145"
log = "0.4.17"
config = "0.13.2"
derive_more = "0.99.17"
serde_json = "1.0.86"
chrono =  "0.4.22"
url = "2.3.1"
console = "0.15.2"
exitcode = "1.1.2"
ethers = "1.0.0"
clap = { version = "4.0.19", features = ["cargo"] }
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }
reqwest = { version = "0.11.12", features = ["json", "rustls-tls"] }

[dependencies.sea-orm]
version = "0.10.2"
features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "sqlx-mysql",
  "runtime-tokio-rustls"
]
